// src/components/preact/Counter.jsx
import { useState } from 'preact/hooks';

function Counter() {
  const [count, setCount] = useState(1);

  return (
    <div data-testid="preact-counter">
      <span>Preact counter: {count}</span>
      {' '}
      <button onClick={() => setCount(count + 1)}>+1</button>
    </div>
  );
}

export default Counter;

// src/components/vue/Counter.vue
<template>
  <div data-testid="vue-counter">
    <span>Vue counter: {{ count }}</span>
    {{' '}}
    <button @click="increment">+1</button>
  </div>
</template>

<script>
import { ref } from 'vue';

export default {
  name: 'Counter',
  setup() {
    const count = ref(1);

    const increment = () => {
      count.value += 1;
    };

    return {
      count,
      increment,
    };
  },
};
</script>
